// Generated by gencpp from file cartographer_ros_msgs/FinishTrajectory.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_FINISHTRAJECTORY_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_FINISHTRAJECTORY_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/FinishTrajectoryRequest.h>
#include <cartographer_ros_msgs/FinishTrajectoryResponse.h>


namespace cartographer_ros_msgs
{

struct FinishTrajectory
{

typedef FinishTrajectoryRequest Request;
typedef FinishTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FinishTrajectory
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::FinishTrajectory > {
  static const char* value()
  {
    return "0feba73841cb434875547ca2a563a021";
  }

  static const char* value(const ::cartographer_ros_msgs::FinishTrajectory&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::FinishTrajectory > {
  static const char* value()
  {
    return "cartographer_ros_msgs/FinishTrajectory";
  }

  static const char* value(const ::cartographer_ros_msgs::FinishTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::FinishTrajectoryRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::FinishTrajectory > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::FinishTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::FinishTrajectory >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::FinishTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::FinishTrajectoryRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::FinishTrajectory > 
template<>
struct DataType< ::cartographer_ros_msgs::FinishTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::FinishTrajectory >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::FinishTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::FinishTrajectoryResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::FinishTrajectory > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::FinishTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::FinishTrajectory >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::FinishTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::FinishTrajectoryResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::FinishTrajectory > 
template<>
struct DataType< ::cartographer_ros_msgs::FinishTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::FinishTrajectory >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::FinishTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_FINISHTRAJECTORY_H
